config/routes.rb
LostTie4::Application.routes.draw do
  resources :entries

  resources :categories

  devise_for :users

  mount Blogit::Engine => '/blog', as: 'blogit_engine'

  root to: 'home#index'

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  resources :portfolio, only: :index
  get '/portfolio' => 'portfolio#index'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image_url  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	has_and_belongs_to_many :entries
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  image_url   :string(255)
#  blog_url    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Entry < ActiveRecord::Base
	has_and_belongs_to_many :categories
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :message

  validates :name, :email, :subject, :message, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  alias                  :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :alias
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :image_url)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :description, :image_url, :blog_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  	@entries = Entry.all
  	@categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.association :entries %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.image_url %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @category.image_url %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/contact/contacts/new.html.erb
<div class="row">
  <div class="large-9 columns">

    <h3>We'd love to hear from you!</h3>
    <p>
      Drop us a line or shoot over an email. You can even contact a team member with a specific question. We're excited to hear about your project!
    </p>
    <h5 class="title" style="left: 199px;">
      <a href="#panel2">The Team</a>
    </h5>
    <div class="content" data-slug="panel2" style="">
      <ul class="large-block-grid-5">
        <li>
          <a href="mailto:contact@losttie.com">
            Jason Rylance
          </a>
          <p>Director, Lead Developer<br>
          361-288-4278</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Andrew Foster
          </a>
          <p>Graphic Design, Marketing<br>
          210-422-2054</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Eric Whittley
          </a>
          <p>User Experience, Lead Technical<br>
          512-588-2452</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Fabian Puente
          </a>
          <p>Graphic Design<br>
          512-789-4653</p>
        </li>
      </ul>
    </div>
    <div class="content" data-slug="panel1" style="">
      <%= simple_form_for @contact, :url =>
      contacts_path do |f| %>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Name</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :name, :label =>false, :placeholder => 'Jane Doe' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Email</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :email, :label =>false, :placeholder => 'jane@doeco.com' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Company</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :subject, :label =>false, :placeholder => 'Doe Co' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Message</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :message, :as =>
          :text, :label => false, :placeholder => 'I want to build a neat website!' %>
        </div>
      </div>
      <button type="submit" class="radius button">Send</button>
      <% end %>
    </div>
  </div>
  <div class="large-3 columns">
    <h5>Phone or Email</h5>
    <p>
      361-288-4278
      <br>
      <a href="mailto:contact@losttie.com">contact@losttie.com</a>
    </p>
  </div>
</div>

app/views/contact/new.html.erb
<div class="row">
  <div class="large-9 columns">

    <h3>We'd love to hear from you!</h3>
    <p>
      Drop us a line or shoot over an email. You can even contact a team member with a specific question. We're excited to hear about your project!
    </p>
    <h5 class="title" style="left: 199px;">
      <a href="#panel2">The Team</a>
    </h5>
    <div class="content" data-slug="panel2" style="">
      <ul class="large-block-grid-5">
        <li>
          <a href="mailto:contact@losttie.com">
            Jason Rylance
          </a>
          <p>Director, Lead Developer<br>
          361-288-4278</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Andrew Foster
          </a>
          <p>Graphic Design, Marketing<br>
          210-422-2054</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Eric Whittley
          </a>
          <p>User Experience, Lead Technical<br>
          512-588-2452</p>
        </li>
      </ul>
    </div>
    <div class="content" data-slug="panel1" style="">
      <%= simple_form_for @message, :url =>
      contact_path do |f| %>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Name</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :name, :label =>false, :placeholder => 'Jane Doe' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Email</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :email, :label =>false, :placeholder => 'jane@doeco.com' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Company</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :subject, :label =>false, :placeholder => 'Doe Co' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Message</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :message, :as =>
          :text, :label => false, :placeholder => 'I want to build a neat website!' %>
        </div>
      </div>
      <button type="submit" class="radius button">Send</button>
      <% end %>
    </div>
  </div>
  <div class="large-3 columns">
    <h5>Phone or Email</h5>
    <p>
      361-288-4278
      <br>
      <a href="mailto:contact@losttie.com">contact@losttie.com</a>
    </p>
  </div>
</div>

app/views/entries/_form.html.erb
<%= simple_form_for(@entry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image_url %>
    <%= f.input :blog_url %>
    <%= f.association :categories %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Blog url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.description %></td>
        <td><%= entry.image_url %></td>
        <td><%= entry.blog_url %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @entry.image_url %>
</p>

<p>
  <strong>Blog url:</strong>
  <%= @entry.blog_url %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/home/_slider.html.erb
<div id="sequence-theme">
    <div id="sequence">
        <ul class="sequence-canvas">
            <li class="animate-in">
                <div class="intro">
                    <h2>A website can help your business earn you money</h2>
                    <h3></h3>
                </div>
                <img class="floating" src="/assets/images/floating.png" alt="floating" />
                <img class="floating-shadow" src="/assets/images/floating-shadow.png" />
            </li>
            <li>
                <img class="ipad" src="/assets/images/ipad.png" alt="iPad" />
                <div class="slide2">
                    <h2>A one time investment can yield an ongoing ROI.</h2>
                    <p>Sliders using CSS3 transitions</p>
                </div>
                <img class="ipad-shadow" src="/assets/images/ipad-shadow.png" />
            </li>
            <li>
                <div class="slide3">
                    <h2>Cutting Edge</h2>
                    <p>The edge has not been cut!</p>
                </div>
                <img class="iphone2" src="/assets/images/iphone.png" alt="iPhone4" />
                <img class="iphone2-shadow" src="/assets/images/iphone-shadow.png" />
                <img class="iphone3" src="/assets/images/iphone.png" alt="iPhone4" />
                <img class="iphone3-shadow" src="/assets/images/iphone-shadow.png" />
                <img class="iphone4" src="/assets/images/iphone.png" alt="iPhone4" />
                <img class="iphone4-shadow" src="/assets/images/iphone-shadow.png" />
            </li>
        </ul>
    </div>
</div>

app/views/home/index.html.erb
<div class="row">

  <div class="large-6 columns text-center">
    <%= image_tag "floating.png", :alt=>"floating alien mascot" %></div>

  <div class="large-6 columns marginalize-top">
    <h3 class="show-for-small">We create solutions for lost websites</h3>
    <h4 class="hide-for-small">We create solutions for lost websites</h4>
    <h5 class="subheader">
      A website should help market your business and bring in new revenue. Let us take care of the hard stuff and help maximize the return on your website.
    </h5>
    <br>
    <h3 class="show-for-small">Offering Service in Corpus Christi</h3>
    <h4 class="hide-for-small">Offering Service in Corpus Christi</h4>
    <h5 class="subheader">
      Our primary area of operation is in Corpus Christi, TX.  As such, we typically work with clients from the surrounding areas - if you are outside of town don't hesitate to call and see if we can find a solution for your area.
    </h5>
  </div>

</div>
<hr>
<div class="row">

  <div class="hide-for-small large-6 columns text-right marginalize-top">
    <h3 class="show-for-small">
      We offer web development services that make your business better
    </h3>
    <h4 class="hide-for-small">
      We offer web development services that make your business better
    </h4>
    <h5 class="subheader">
      An effective website turns a visitor into a customer. By understanding the
      <span>science</span>
      behind this we can create custom designed websites which make your business stand out.
    </h5>
  </div>

  <div class="large-6 columns text-center">
    <%= image_tag "standing.png", :alt=>"standing alien mascot" %></div>

  <div class="show-for-small large-6 columns">
    <h3 class="show-for-small">
      We offer web development services that make your business better.
    </h3>
    <h4 class="hide-for-small">
      We offer web development services that make your business better.
    </h4>
    <h5 class="subheader">
      An effective website turns a visitor into a customer. By understanding the
      <span>science</span>
      behind this we can create custom designed websites which make your business stand out.
    </h5>
  </div>

</div>
<hr>
<div class="row" id="services">
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/shopping_cart.png", :alt=>
      "shopping cart" %>
      <h4 class="show-for-small">Create New Shopping Experiences</h4>
      <h4 class="hide-for-small">Create New Shopping Experiences</h4>
    </div>
    <p class="subheader text-center">
      Online stores are a great way to expand your business.  Not only can we get your store online, we can create a marketing tactic that will yield predictable sales.
    </p>
  </div>
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/custom_software.png", :alt=>
      "customized software" %>
      <h4 class="show-for-small">Forge Customized Tools For Your Business</h4>
      <h4 class="hide-for-small">Forge Customized Tools For Your Business</h4>
    </div>
    <p class="subheader text-center">
      We build web applications that are specially-made to meet the needs of your business. Need to allow your customers to set up appointments? Want to track monthly quotas and performance? We've got this covered.
    </p>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/virtual_business_card.png", :alt=>
      "virtual business card" %>
      <h4 class="show-for-small">Set Up Quick Profiles</h4>
      <h4 class="hide-for-small">Set Up Quick Profiles</h4>
    </div>
    <p class="subheader text-center">
      Maybe you just need something simple. We can set up single page profiles that convey what you do without the cost of a large-scale website.
    </p>
  </div>
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/event_broadcaster.png", :alt=>
      "microphone" %>
      <h4 class="show-for-small">Broadcast Your Event</h4>
      <h4 class="hide-for-small">Broadcast Your Event</h4>
    </div>
    <p class="subheader text-center">
      You have a one-time event, and it's coming up quick. We can provide a more rapid turnaround time for these situations.
    </p>
  </div>

</div>

app/views/layouts/_footer.html.erb
<div class="large-12 columns">
  <hr>
  <div class="row">
    <div class="large-5 columns">
      <p>Lost Tie LLC Call Jason: 361-288-4278</p>
    </div>
    <div class="large-7 columns">
      <ul class="inline-list right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Services", root_path(:anchor => "services") %>
        <li><%= link_to "Portolio", portfolio_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="nav-container contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <%= link_to image_tag("logo.png", :alt=>"logo"), root_path, :class => 'logo' %></li>
      <li class="toggle-topbar menu-icon">
        <a href="#">
          <span><text class="show-for-medium">Menu</text></span>
        </a>
      </li>
      <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% end %>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->

      <!-- Right Nav Section -->
      <ul class="right">
        <li>
          <%= link_to "Home", root_path, :class =>('active' if current_page?root_path) %></a>
        </li>
        <li>
          <%= link_to "Portfolio", portfolio_path, :class =>('active' if current_page?portfolio_path) %>
        </li>
        <li>
          <%= link_to "Contact", contact_path, :class =>('active' if current_page?contact_path) %></a>
        </li>
      </ul>
    </section>
  </nav>
  <hr class="hide-for-small">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Lost Tie Web Development" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Professional web development for Corpus Christi, TX." %>
  ">
  <%= stylesheet_link_tag "application", :media =>
  "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
  <%= favicon_link_tag 'favicon.png' %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31605971-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
  </head>
<body class="<%= controller_name %>
  <%= action_name %>
  ">
  <div id="container" class="container">
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %></header>
    <div id="main" role="main">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <footer class="row">
      <%= render 'layouts/footer' %></footer>
  </div>
  <!--! end of #container -->
</body>
</html>

app/views/portfolio/index.html.erb
<ul id="filter">  
    <li class="current"><a href="#">All</a></li>  
    <% @categories.each do |category| %>
      <li><a href="#"><%= category.name %></a></li>
    <% end %> 
</ul>  

<div id="portfolio" class="row">
  <% @entries.each do |entry| %>
    <div class="large-4 small-6 entry-container <% entry.categories.each do |c| %><%= c.name.downcase.gsub(' ', '-')+' ' %><% end %>"><img src="<%= entry.image_url %>"></div>
  <% end %>
</div>